// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asftszmkytarrdrkjbgj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzZnRzem1reXRhcnJkcmtqYmdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MDkzMjksImV4cCI6MjA2Mzk4NTMyOX0.mao_mrErbuFqB0aStUsrq058o2BfYNwMg0Eoz-7aYg8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);